language: python
python:
  - "3.5"  # Python 3.5 still needs to be installed on Travis-CI

services:
  - docker

env:
  - TOX_ENV=py27 SCENARIO=true
  - TOX_ENV=py34 SCENARIO=true
  - TOX_ENV=py35 SCENARIO=false
  - TOX_ENV=pypy26 SCENARIO=false
  - TOX_ENV=pep8 SCENARIO=false

install:
  - pip install tox coveralls

sudo: required
script:
  - NOSE_VERBOSE=0 tox -e $TOX_ENV

after_success:
  - coveralls
