language: python

matrix:
  include:
  - python: "2.7"
    services: docker
    sudo: required
    script: 
    - NOSE_VERBOSE=0 tox -e pep8
    - NOSE_VERBOSE=0 tox -e py27
    - tox -e scenario
  - python: "3.4"
    services: docker
    sudo: required
    script:
    - NOSE_VERBOSE=0 tox -e pep8
    - NOSE_VERBOSE=0 tox -e py34
    - tox -e scenario
  - python: "3.5"
    script:
    - NOSE_VERBOSE=0 tox -e pep8
    - NOSE_VERBOSE=0 tox -e py35
  - python: "pypy2.6"
    script:
    - NOSE_VERBOSE=0 tox -e pypy26

install:
  - pip install tox coveralls

after_success:
  - coveralls
