language: python
python:
  - "3.5"  # Python 3.5 still needs to be installed on Travis-CI

env:
  - TOX_ENV=openstack

services:
  - docker

sudo: required  # Required to enable Docker service

install:
  - docker build -t ut_mininet ryu/tests/docker/mininet/
  - CID=`docker run --privileged -t -d ut_mininet`; docker rm -f $CID  # Test container
  - pip install tox coveralls

script:
  - bash -xe ryu/tests/integrated/openstack/fullstack_main.sh

after_success:
  - coveralls
