language: python

matrix:
  include:
  - env: TOX_ENV=py27
    python: "2.7"
    services: docker
    sudo: required
    script: 
    - tox -e scenario
  - env: TOX_ENV=py34
    python: "3.4"
    services: docker
    sudo: required
    script:
    - tox -e scenario
  - env: TOX_ENV=py35
    python: "3.5"
  - env: TOX_ENV=pypy26
    python: "3.5"  # Python 3.5 still needs to be installed on Travis-CI
  - env: TOX_ENV=pep8
    python: "3.5"

install:
  - pip install tox coveralls

script:
  - NOSE_VERBOSE=0 tox -e $TOX_ENV

after_success:
  - coveralls
